### ISSUE TITLE
Package versions

### ISSUE THREAD

**Issue by SHIV1198** [gfleetwood/hate-speech#5]
Sir I am trying to run this project on my pc but looks like it has various compatibility issues.
Can you please tell the versions of python and sklearn you have used and guide me how to overcome following errors??
![error](https://user-images.githubusercontent.com/63007239/90308508-aedc8080-defd-11ea-9cd7-5739547ece84.jpg)

**Comment by gfleetwood** [comment]
Hey, sorry. Just seeing this. I did this project years ago when tracking requirements wasn't on my mind. I couldn't begin to tell you where to start since all the package versions I used are now really old.

I would suggest starting from scratch using up to date libraries and a library like spacy.

**Comment by gfleetwood** [comment]
Actually, my bad. There is a requirements.txt file in the repo. You can use that.
